version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket currency-exchange-api-sam --output-template-file packaged-template.yml
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-bucket-forex-api --region eu-west-2 --output-template-file packaged-template-london.yml
artifacts:
  files:
    - packaged-template.yml
    - packaged-template-london.yml