version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-bucket-forex-api-ireland --region eu-west-1 --output-template-file packaged-template-eu-west.yml
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-bucket-forex-api-germany --region eu-central-2 --output-template-file packaged-template-eu-central.yml
artifacts:
  files:
    - packaged-template-eu-west.yml
    - packaged-template-eu-central.yml