AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  forex-api-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  ForexAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: currency-exchange/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ForexAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /currency-exchange-rate
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ForexApi:
    Description: "API Gateway endpoint URL for Prod stage for Forex API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ForexAPIFunction:
    Description: "Forex API Lambda Function ARN"
    Value: !GetAtt ForexAPIFunction.Arn
  ForexAPIFunctionIamRole:
    Description: "Implicit IAM Role created for Forex API App function"
    Value: !GetAtt ForexAPIFunctionRole.Arn
