AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  forex-api-app
  

Globals:
  Function:
    Timeout: 15

Resources:

  CurrencyExchangeAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaTokenAuhtorizer
        Authorizers:
          LambdaTokenAuhtorizer:
            FunctionArn: !GetAtt CurrencyAuthFunction.Arn

  ForexAPIFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: currency-exchange/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ForexAPI:
          Type: Api 
          Properties:
            RestApiId: !Ref CurrencyExchangeAPI
            Path: /currency-exchange-rate
            Method: get
            

  CurrencyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./authorizer
      Handler: handler.authorizer
      Runtime: python3.8

Outputs:
  ForexApi:
    Description: "API Gateway endpoint URL for Prod stage for Forex API Gateway"
    Value: !Sub "https://${CurrencyExchangeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ForexAPIFunction:
    Description: "Forex API Lambda Function ARN"
    Value: !GetAtt ForexAPIFunction.Arn
  ForexAPIFunctionIamRole:
    Description: "Implicit IAM Role created for Forex API App function"
    Value: !GetAtt ForexAPIFunctionRole.Arn
